import Head from "next/head";
import MainContent from "../components/main-content/MainContent";
import NoteCard from "../components/NoteCard";
import Sidebar from "../components/sidebar/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>DNoteBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      {/* Body */}
      <div className="flex">
        <Sidebar />
        <MainContent />
      </div>
      {/* Footer */}
    </div>
  );
}
